// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43L-7SMHFd3vJjSkhMDXMzbDXrfvHE_Q',
    appId: '1:475485784616:web:1b131f3520eef811be431d',
    messagingSenderId: '475485784616',
    projectId: 'cloud-wechat-server',
    authDomain: 'cloud-wechat-server.firebaseapp.com',
    storageBucket: 'cloud-wechat-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_JkZt9AMlq4Uq0bZA5kku0T-5VRbJ8Q',
    appId: '1:475485784616:android:79529749f23f6293be431d',
    messagingSenderId: '475485784616',
    projectId: 'cloud-wechat-server',
    storageBucket: 'cloud-wechat-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29O_lPVv-pZjRXlDZKWCH1NNb1MX54h0',
    appId: '1:475485784616:ios:d8265e86641f20b6be431d',
    messagingSenderId: '475485784616',
    projectId: 'cloud-wechat-server',
    storageBucket: 'cloud-wechat-server.appspot.com',
    iosBundleId: 'com.we.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29O_lPVv-pZjRXlDZKWCH1NNb1MX54h0',
    appId: '1:475485784616:ios:dd91806f5fe43a47be431d',
    messagingSenderId: '475485784616',
    projectId: 'cloud-wechat-server',
    storageBucket: 'cloud-wechat-server.appspot.com',
    iosBundleId: 'com.we.chat.RunnerTests',
  );
}
